ALTER TABLE orders 
    ADD COLUMN `status` VARCHAR(30), 
    ADD COLUMN `table` INT,
    ADD COLUMN last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD CONSTRAINT ck_status_orders CHECK (`status` IN ('PENDENTE', 'EM PREPARO', 'DISPONIVEL') );
