UPDATE orders SET status = 'DISPONIVEL', `table` = NULL WHERE id = 1;
UPDATE orders SET status = 'EM PREPARO', `table` = NULL WHERE id = 2;
UPDATE orders SET status = 'DISPONIVEL', `table` = 1 WHERE id = 3;
UPDATE orders SET status = 'EM PREPARO', `table` = NULL WHERE id = 4;
UPDATE orders SET status = 'DISPONIVEL', `table` = 1 WHERE id = 5;
UPDATE orders SET status = 'DISPONIVEL', `table` = NULL WHERE id = 6;
UPDATE orders SET status = 'EM PREPARO', `table` = 2 WHERE id = 7;
UPDATE orders SET status = 'EM PREPARO', `table` = NULL WHERE id = 8;
UPDATE orders SET status = 'PENDENTE', `table` = 3 WHERE id = 9;
UPDATE orders SET status = 'PENDENTE', `table` = NULL WHERE id = 10;
UPDATE orders SET status = 'PENDENTE', `table` = 4 WHERE id = 11;
