spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/orderize?createDatabaseIfNotExist=true
    username: client
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
