spring:
  profiles:
    active: dev
  flyway:
    locations: classpath:db/migration/mariadb
    enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000


external-spoonacular:
  url: https://api.spoonacular.com
  api:
    key: 59f94a96a38c4681b31619aacd7e5ec4 
