spring:
  profiles:
    active: dev
  flyway:
    locations: classpath:db/migration/mariadb


external-spoonacular:
  url: https://api.spoonacular.com
  api:
    key: 59f94a96a38c4681b31619aacd7e5ec4 
