spring:
  datasource:
    url: jdbc:mariadb://10.0.0.149:3306/orderize?createDatabaseIfNotExist=true&useSSL=true&requireSSL=true
    username: client
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
