spring:
  datasource:
    url: jdbc:mariadb://orderize-db.mysql.database.azure.com:3306/orderize?createDatabaseIfNotExist=true&useSSL=true&requireSSL=true
    username: dev
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
