name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - development
      - feature/infra/build-docker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (latest)
        uses: docker/build-push-action@v4
        with: 
          context: .
          push: true
          tags: santthiago/orderize-backend:latest
          build-args: |
            TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}
            SPRING_PROFILES_ACTIVE=prod

      - name: Build and push Docker image (dev)
        uses: docker/build-push-action@v4
        with: 
          context: .
          push: true
          tags: santthiago/orderize-backend:dev
          build-args: |
            TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}
            SPRING_PROFILES_ACTIVE=dev