name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with: 
          context: .
          push: true
          tags: santthiago/orderize-backend:latest
          build-args:
            token_secret: ${{ secrets.TOKEN_SECRET }}
            spring_datasource_url: ${{ secrets.SPRING_DATASOURCE_URL }}
            spring_datasource_username: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
            spring_datasource_password: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
